version: '3.4'
services:
  react-nginx-app:
    container_name: tri-docker-container-react-nginx-app # tag name container create
    stdin_open: true
    build:
      context: . # dicrectory of Dockerfile
      dockerfile: Dockerfile # name of file Dockerfile
    image: 'tri-image-codebase' #  create name for image created by Dockerfile
    ports:
      - "29014:80"
    environment:
      - CHOKIDAR_USEPOLLING=true # rebuild app